name: Poke Plaza

on:
  pull_request:
    branches: [main, dev]

jobs:
  format:
    name: Format Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm config set optional true
      - run: npm ci
      - run: npx prettier . --check

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm config set optional true
      - run: npm ci
      - run: npm run lint

  build:
    name: Build Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm config set optional true
      - run: npm ci

      - run: npm run build
